# Keep JWT keys/email-credentials private
# Generate all random key for production
jwt:
  key: 12345678 # Do NOT use this in production. Use any random key generation tool.
  token-expiration-time:
    access: 864_000_000 # 10 days
    password-reset: 9000_00 # 15 minutes


spring:
  mail:
    host: # mail host
    port: 587
    username: # mail username
    password: # mail password

    # Other properties
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000